#! /bin/bash

ip a | grep "mtu 1500"
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf && sysctl -p
cat /etc/sysctl.conf | grep "net.ipv4.ip_forward=1"

systemctl enable wg-quick@wg0.service
systemctl start wg-quick@wg0.service
systemctl status wg-quick@wg0.service